@serial
@cradle_hostnet
Feature: Host-network-backed services (served through cradle, not kube-proxy)
  A service whose backend runs in the host network (its IP is the node's own
  address — e.g. the API server) is now served by the cradle datapath. The
  client's request DNATs to the node IP and is delivered locally to the host
  process; the reply is generated by the node's own stack and leaves toward
  the client pod, where a clsact-egress reverse-NAT rewrites its source back
  to the VIP. Kernel forwarding is off, so the pod reaching the service and
  seeing a VIP-sourced reply proves the eBPF datapath (ingress DNAT + egress
  reverse-NAT) carried it. Design: docs/design/kube-proxy-dualstack.md (K4).

  Topology:
  ```
   pod1(10.244.0.2) ─ crdl* [node: cradle, host-net HTTP on 203.0.113.1:9000] n0 ── (ext)
                       service 10.96.0.100:80 → 203.0.113.1:9000 (the node itself)
  ```

  Scenario: A pod reaches a host-network backend via a ClusterIP
    Given a clean test environment
    When I create namespace "node"
    And I create namespace "ext"
    And I create namespace "pod1"
    And I connect namespace "node" interface "n0" to namespace "ext" interface "eth0"
    And I add address "203.0.113.1/24" to interface "n0" in namespace "node"
    And I add address "203.0.113.9/24" to interface "eth0" in namespace "ext"
    And I disable IPv4 forwarding in namespace "node"
    And I start cradle CNI node in namespace "node" with config "node.json" serving gRPC as "ctl"
    And I run CNI ADD for container "pod1" in pod namespace "pod1" on node "node" with config "cni.json" expecting "10.244.0.2"
    # The "host-network backend" is a server in the node's own namespace,
    # bound to the node IP (its address == the node, like a hostNetwork pod).
    And I serve HTTP "hostnet-ok" in namespace "node" bound to "203.0.113.1"
    And I apply cradle config "svc.json" to namespace "node" via gRPC as "ctl"
    Then HTTP GET "http://10.96.0.100/" from namespace "pod1" should contain "hostnet-ok"
    And the cradle stat "l4_dnat" in namespace "node" via gRPC as "ctl" should be nonzero
    And the cradle stat "l4_snat" in namespace "node" via gRPC as "ctl" should be nonzero

  Scenario: Teardown topology
    Given the test topology exists
    When I stop HTTP in namespace "node"
    And I stop cradle CNI node in namespace "node"
    And I delete namespace "pod1"
    And I delete namespace "ext"
    And I delete namespace "node"
    Then the test environment should be clean
